# Generated by Django 4.0.1 on 2022-01-28 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Title must be longer than 1 character')]),
        ),
    ]
