# Generated by Django 4.0.1 on 2022-01-29 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='link',
            field=models.URLField(help_text='Enter any associated URL, if any', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(help_text='Enter body of the note', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Enter title of the note', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Title must be longer than 1 character')]),
        ),
    ]
