# Generated by Django 4.0.1 on 2022-01-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_link_alter_note_body_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Enter any associated URL, if any'),
            preserve_default=False,
        ),
    ]
