# Generated by Django 4.0.1 on 2022-01-29 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='link',
            field=models.URLField(blank=True, help_text='Enter any associated URL, if any; must begin with http or https', validators=[django.core.validators.URLValidator(message='Enter a valid http or https URL', schemes=['http', 'https'])]),
        ),
    ]
