# Generated by Django 4.0.1 on 2022-01-29 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_note_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='link',
            field=models.URLField(blank=True, help_text='Enter an optional URL beginning with http or https', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
