# Generated by Django 4.0.1 on 2022-01-29 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_note_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='link',
            field=models.URLField(blank=True, error_messages={'invalid': 'URL must start with http or https'}, help_text='Enter an optional URL beginning with http or https', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
